# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/challenge"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/functions/*"
  to = "/functions/:splat"
  status = 200
  force = true

  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' https://*.supabase.co https://res.cloudinary.com https://www.facebook.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval'
        https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/
        https://onsite.optimonk.com https://cdn-asset.optimonk.com https://gs-cdn.optimonk.com
        https://web.optimonk.com https://web-integration.optimonk.com
        https://cdn.retainful.app https://cdn.retainful.com
        https://agentivehub.com https://assets.mailerlite.com https://groot.mailerlite.com
        https://assets.mlcdn.com https://fonts.mailerlite.com
        https://connect.facebook.net https://www.googletagmanager.com;
      worker-src 'self' blob:;
      style-src 'self' 'unsafe-inline'
        https://fonts.googleapis.com https://cdn-asset.optimonk.com
        https://agentivehub.com https://assets.mailerlite.com https://assets.mlcdn.com
        https://fonts.mailerlite.com;
      style-src-elem 'self' 'unsafe-inline'
        https://fonts.googleapis.com https://cdn-asset.optimonk.com
        https://agentivehub.com https://assets.mailerlite.com https://assets.mlcdn.com
        https://fonts.mailerlite.com;
      img-src 'self' data: blob: https://res.cloudinary.com https://images.unsplash.com
        https://bnumwujvaribzfexpmmc.supabase.co
        https://editor-upload-cdn.optimonk.com https://placehold.co
        https://agentive-file-storage.s3.amazonaws.com
        https://www.facebook.com https://connect.facebook.net
        https://i.ytimg.com https://yt3.ggpht.com;
      font-src 'self' data: https://fonts.gstatic.com https://fonts.mailerlite.com https://cdn-custom.optimonk.com;
      media-src 'self' https://res.cloudinary.com https://bnumwujvaribzfexpmmc.supabase.co;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co
        https://ipinfo.io
        https://onsite.optimonk.com
        https://cdn-account.optimonk.com https://front.optimonk.com
        https://cdn-limit.optimonk.com https://jfapiprod.optimonk.com
        https://cdn-renderer.optimonk.com https://cdn.retainful.com
        https://agentivehub.com
        https://restcountries.com
        https://connect.facebook.net https://www.facebook.com
        https://capi-data04.com https://capig.datah04.com
        https://res.cloudinary.com
        https://www.google-analytics.com;
      frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com https://www.google.com;
      child-src 'self' https://www.youtube.com https://www.youtube-nocookie.com https://www.google.com;
      frame-ancestors 'none';
      form-action 'self' https://assets.mailerlite.com https://www.facebook.com;
      base-uri 'self';
      object-src 'none';
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
